# Generated by Django 4.0.6 on 2022-09-20 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, help_text='Writable', verbose_name='availability')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Set the date', unique=True, verbose_name='date')),
                ('start', models.TimeField(default=datetime.time(9, 0), help_text='Set the beginning of the work day', validators=[schedule.models.is_half_hour_validator], verbose_name='start')),
                ('finish', models.TimeField(default=datetime.time(18, 0), help_text='Set the end of the working day', validators=[schedule.models.is_half_hour_validator], verbose_name='end')),
                ('start_break_time', models.TimeField(blank=True, default=datetime.time(13, 0), help_text='select the start time of the break, or leave the field blank if there is none', validators=[schedule.models.is_half_hour_validator], verbose_name='start break')),
                ('finish_break_time', models.TimeField(blank=True, default=datetime.time(14, 0), help_text='select the finish time of the break, or leave the field blank if there is none', validators=[schedule.models.is_half_hour_validator], verbose_name='finish break')),
                ('slug', models.SlugField(help_text='choose name', unique=True, verbose_name='Name of day')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'db_table': 'Days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('MAT', 'Maths'), ('RUS', 'Russian')], default='ENG', help_text='Select subject', max_length=3, verbose_name='subject')),
                ('start', models.TimeField(help_text='Set start of lesson', validators=[schedule.models.is_half_hour_validator], verbose_name='start of lesson')),
                ('duration', models.TimeField(choices=[(datetime.time(0, 30), '30 minute'), (datetime.time(1, 0), '1 hour'), (datetime.time(2, 0), '2 hours')], default=datetime.time(1, 0), help_text='select lesson duration', verbose_name='lesson duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, help_text='Comment', max_length=512, verbose_name='comment')),
                ('day', models.ForeignKey(help_text='Set the day', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.workday', verbose_name='day')),
                ('user', models.ForeignKey(help_text='Set user', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'Lessons',
                'ordering': ['day', 'start'],
                'unique_together': {('day', 'start')},
            },
        ),
    ]
